"""Contract-compatible routes."""
import asyncio
import logging
import re
from datetime import datetime
from typing import Any, Literal

from fastapi import APIRouter, BackgroundTasks, Body, Depends, HTTPException, Query, status
from pydantic import AliasChoices, BaseModel, ConfigDict, EmailStr, Field, model_validator
from sqlalchemy.orm import Session

from app.controllers import contract_controllers as controllers
from app.crud import message as message_crud
from app.crud import owner as owner_crud
from app.database import get_db
from app.middleware.auth import require_auth
from app.core.config import settings
from app.models import Device, Message, Owner, PushToken, ZoneMessageEvent
from app.models.message import MessageVisibility
from app.schemas.schemas import MessageVisibilityEnum, ZoneMessageCreate, ZoneMessageResponse
from app.utils.api_response import success_response
from app.websocket.manager import ws_manager
from app.domain.message_types import CanonicalMessageType, MessageScope, normalize_message_type, type_category, type_scope
from app.services import guest_api_service
from app.services.access_policy import can_message_owner
from app.services import message_block_service
from app.services.account_type_policy import assert_owner_may_edit_network_id
from app.services.owner_home_service import apply_owner_home_geocode, sync_owner_home_from_address

router = APIRouter(tags=["contract"])


class LoginRequest(BaseModel):
    email: EmailStr
    password: str

    model_config = {
        "json_schema_extra": {
            "example": {
                "email": "admin@demo.com",
                "password": "StrongPass123!",
            }
        }
    }


class RegisterRequest(BaseModel):
    name: str = Field(min_length=1, description="First and last name from setup wizard")
    email: EmailStr
    password: str = Field(min_length=8)
    registrationCode: str | None = Field(
        default=None,
        min_length=1,
        description=(
            "Required when registrationType is ADMINISTRATOR: echo the code from "
            "GET /utils/registration-code (preferred) or GET /owners/registration-code, "
            "or tier code FREE (stateless; always accepted for admin signup)."
        ),
    )
    accountType: Literal["PRIVATE", "PRIVATE_PLUS", "EXCLUSIVE", "ENHANCED", "ENHANCED_PLUS"]
    registrationType: Literal["ADMINISTRATOR", "USER"] = "ADMINISTRATOR"
    accountOwnerId: int | None = Field(
        default=None,
        ge=1,
        description="Required for USER registration when linking to an existing administrator account",
    )
    zoneId: str | None = Field(
        default=None,
        description="Network ID entered manually, generated by system, or scanned via QR",
    )
    address: str = Field(min_length=1, description="Street/city/province/country")

    @model_validator(mode="before")
    @classmethod
    def normalize_account_type(cls, data: Any) -> Any:
        if not isinstance(data, dict):
            return data

        payload = dict(data)
        account_type = payload.get("accountType")
        if not isinstance(account_type, str):
            return payload

        normalized = account_type.strip().upper()
        normalized = normalized.replace("-", "_").replace(" ", "_")
        normalized = normalized.replace("_+","_PLUS").replace("+", "_PLUS")
        alias_map = {
            "ENHANCE": "ENHANCED",
            "ENHANCE_PLUS": "ENHANCED_PLUS",
        }
        payload["accountType"] = alias_map.get(normalized, normalized)
        registration_type = payload.get("registrationType")
        if isinstance(registration_type, str):
            role_normalized = registration_type.strip().upper().replace("-", "_").replace(" ", "_")
            role_alias_map = {
                "ADMIN": "ADMINISTRATOR",
            }
            payload["registrationType"] = role_alias_map.get(role_normalized, role_normalized)
        return payload

    model_config = {
        "json_schema_extra": {
            "example": {
                "name": "Avery Stone",
                "email": "avery@example.com",
                "password": "strong-password-123",
                "accountType": "PRIVATE",
                "registrationType": "ADMINISTRATOR",
                "zoneId": "ZONE-7A29",
                "address": "101 Main St, Denver, CO, USA",
                "registrationCode": "FREE",
            }
        }
    }


class ZoneUpsertRequest(BaseModel):
    name: str
    type: Literal[
        "polygon",
        "circle",
        "grid",
        "dynamic",
        "proximity",
        "object",
        "geofence",
        "warn",
        "alert",
        "restricted",
        "emergency",
        "communal_id",
        "government_local_code",
        "custom_1",
        "custom_2",
    ]
    geometry: dict[str, Any] = Field(default_factory=dict)
    config: dict[str, Any] = Field(default_factory=dict)
    id: str | None = None

    @model_validator(mode="before")
    @classmethod
    def normalize_alias_fields(cls, data: Any) -> Any:
        if not isinstance(data, dict):
            return data

        payload = dict(data)

        if payload.get("type") is None and payload.get("zone_type") is not None:
            payload["type"] = payload["zone_type"]

        if payload.get("id") is None and payload.get("zone_id") is not None:
            payload["id"] = payload["zone_id"]

        if payload.get("geometry") is None and payload.get("geo_fence_polygon") is not None:
            payload["geometry"] = payload["geo_fence_polygon"]

        if "config" not in payload:
            payload["config"] = {}
        if (
            isinstance(payload.get("config"), dict)
            and "h3Cells" not in payload["config"]
            and payload.get("h3_cells") is not None
        ):
            payload["config"]["h3Cells"] = payload["h3_cells"]

        return payload


class MessageCreateRequest(BaseModel):
    zoneId: str = Field(description="Target zone identifier")
    type: str
    text: str = Field(description="Message body")
    metadata: dict[str, Any] = Field(default_factory=dict)

    @model_validator(mode="before")
    @classmethod
    def normalize_type_aliases(cls, data: Any):
        if not isinstance(data, dict):
            return data
        payload = dict(data)
        value = payload.get("type")
        if isinstance(value, str):
            payload["type"] = normalize_message_type(value).value
        return payload


class ChatMessageCreateRequest(BaseModel):
    """Chat payload accepted by /messages (no trailing slash)."""

    message: str = Field(..., min_length=1, max_length=16_384)
    type: str | None = None
    message_type: str | None = Field(
        default=None,
        description="Alias for **type** (e.g. **PERMISSION** / **CHAT**) when **type** is omitted.",
    )
    visibility: Literal["public", "private"] | None = None
    receiver_id: int | None = Field(
        default=None,
        ge=1,
        description="Required when visibility is private; omitted for public",
    )
    guest_id: str | None = Field(default=None, max_length=36)
    zone_id: str | None = Field(
        default=None,
        min_length=1,
        max_length=100,
        validation_alias=AliasChoices("zone_id", "zoneId"),
    )

    @model_validator(mode="after")
    def map_message_type_alias(self):
        if self.type is None and self.message_type:
            self.type = self.message_type
        return self

    model_config = ConfigDict(
        json_schema_extra={
            "examples": [
                {
                    "message": "Team update",
                    "type": "CHAT",
                    "visibility": "private",
                    "receiver_id": 2,
                },
                {
                    "message": "Your host sent a permission update.",
                    "message_type": "PERMISSION",
                    "visibility": "private",
                    "zone_id": "ZN-1XOJPP",
                    "guest_id": "019b2c3d-0000-7000-8000-000000000001",
                },
            ]
        }
    )


class MemberLocationRequest(BaseModel):
    latitude: float = Field(ge=-90, le=90)
    longitude: float = Field(ge=-180, le=180)


class MemberLocationResponse(BaseModel):
    latitude: float
    longitude: float


class MemberListItemResponse(BaseModel):
    id: str
    name: str = Field(description="Owner full name (first + last)")
    first_name: str
    last_name: str
    email: EmailStr
    account_owner_id: int
    address: str
    zone_id: str
    active: bool
    location: MemberLocationResponse | None = None
    lastSeen: str | None = None
    zones: list[str] = Field(default_factory=list)


class ContractSuccessMembersResponse(BaseModel):
    status: Literal["success"]
    data: list[MemberListItemResponse]
    error: None = None


class MemberLocationUpdateResponse(BaseModel):
    latitude: float
    longitude: float
    zones: list[str] = Field(default_factory=list)


class ContractSuccessMemberLocationResponse(BaseModel):
    status: Literal["success"]
    data: MemberLocationUpdateResponse
    error: None = None


class PushTokenRequest(BaseModel):
    token: str = Field(min_length=10)
    # The Expo dev/preview/production builds register an `ExponentPushToken[...]`
    # via expo-notifications. The mobile client sends `platform: "EXPO"` for those
    # tokens; downstream `push_notification_service` already routes EXPO tokens
    # through the Expo Push HTTP API. FCM/APNS remain valid for native sender keys.
    platform: Literal["EXPO", "FCM", "APNS"] = "EXPO"


class OwnerContractResponse(BaseModel):
    id: str
    email: EmailStr
    zone_id: str
    first_name: str
    last_name: str
    account_type: Literal["private", "private_plus", "exclusive", "enhanced", "enhanced_plus"]
    role: Literal["administrator", "user"]
    account_owner_id: int
    address: str
    phone: str | None = None
    map_center: MemberLocationResponse | None = None
    active: bool
    expired: bool
    created_at: datetime
    updated_at: datetime
    api_key: str


class ContractSuccessOwnerMeResponse(BaseModel):
    status: Literal["success"]
    data: OwnerContractResponse
    error: None = None


class ContractLoginUserResponse(BaseModel):
    id: str
    name: str
    accountType: Literal["PRIVATE", "PRIVATE_PLUS", "EXCLUSIVE", "ENHANCED", "ENHANCED_PLUS"]
    registrationType: Literal["ADMINISTRATOR", "USER"]
    accountOwnerId: int
    mapCenter: MemberLocationResponse | None = None


class ContractLoginDataResponse(BaseModel):
    token: str
    user: ContractLoginUserResponse


class ContractSuccessLoginResponse(BaseModel):
    status: Literal["success"]
    data: ContractLoginDataResponse
    error: None = None


class ContractRegisterDataResponse(BaseModel):
    id: str
    email: EmailStr
    zone_id: str
    first_name: str
    last_name: str
    account_type: Literal["private", "private_plus", "exclusive", "enhanced", "enhanced_plus"]
    role: Literal["administrator", "user"]
    account_owner_id: int
    address: str
    phone: str | None = None
    active: bool
    expired: bool
    created_at: datetime
    updated_at: datetime
    api_key: str
    mapCenter: MemberLocationResponse | None = None


class ContractSuccessRegisterResponse(BaseModel):
    status: Literal["success"]
    data: ContractRegisterDataResponse
    error: None = None


class ContractSuccessAnyResponse(BaseModel):
    status: Literal["success"]
    data: Any
    error: None = None


@router.post(
    "/login",
    response_model=ContractSuccessLoginResponse,
    summary="Contract login",
    description=(
        "Mobile login endpoint. Returns token plus user account context for frontend "
        "routing, including account type, registration role, account owner linkage, "
        "and optional map center coordinates."
    ),
    response_description="Login success envelope containing token and user bootstrap context.",
)
async def login(payload: LoginRequest, db: Session = Depends(get_db)):
    # `login` does blocking I/O (DB + optional geocode for legacy owners with
    # NULL coordinates). Run it on the FastAPI thread pool so the event loop
    # stays responsive for other concurrent requests.
    data = await asyncio.to_thread(controllers.login, db, payload.model_dump())
    db.commit()
    return success_response(data)


@router.post(
    "/register",
    status_code=status.HTTP_201_CREATED,
    response_model=ContractSuccessRegisterResponse,
    summary="Contract register",
    description=(
        "Mobile registration endpoint for administrator/user onboarding. Supports all "
        "5 account tiers, role-aware registration, and account owner linking for users. "
        "Exclusive tier does not allow USER members. USER registrations must match the "
        "administrator zone/account type. "
        "Administrators must submit registrationCode: either echo the single-use string "
        "from GET /utils/registration-code (or GET /owners/registration-code) or the "
        "stateless tier code FREE. User registrations do not require a registration code."
    ),
    response_description="Registration success envelope containing newly created owner profile.",
)
async def register(payload: RegisterRequest, db: Session = Depends(get_db)):
    # `register` may invoke the geocoding service for the wizard address —
    # offload to the thread pool so the event loop is not blocked by a slow
    # Nominatim/Photon round-trip.
    data = await asyncio.to_thread(controllers.register, db, payload.model_dump())
    db.commit()
    return success_response(data)


@router.get(
    "/zones",
    response_model=ContractSuccessAnyResponse,
    summary="List contract zones",
    description=(
        "Return zones accessible to the authenticated contract user. Administrators can "
        "see all linked users' zones; users can see their own zones and administrator main zone."
    ),
    responses={
        status.HTTP_401_UNAUTHORIZED: {
            "description": "Authentication token missing or invalid.",
        },
        status.HTTP_403_FORBIDDEN: {
            "description": "Caller is not allowed to access requested zone data.",
        },
    },
    response_description="Success envelope containing caller-visible zone list.",
)
async def get_zones(owner: Owner = Depends(require_auth), db: Session = Depends(get_db)):
    return success_response(controllers.list_zones(db, owner))


@router.get(
    "/me",
    response_model=ContractSuccessOwnerMeResponse,
    summary="Get contract profile",
    description="Return the authenticated owner profile used by mobile client bootstrap.",
    response_description="Success envelope containing authenticated contract profile.",
)
async def get_me(owner: Owner = Depends(require_auth), db: Session = Depends(get_db)):
    try:
        sync_owner_home_from_address(owner)
        db.commit()
        db.refresh(owner)
    except Exception as exc:  # pragma: no cover - never block profile
        logging.getLogger(__name__).warning(
            "Home geocode refresh failed on /me for owner %s: %s", owner.id, exc
        )
        db.rollback()

    map_center: MemberLocationResponse | None = None
    if owner.latitude is not None and owner.longitude is not None:
        map_center = MemberLocationResponse(
            latitude=owner.latitude,
            longitude=owner.longitude,
        )

    data = OwnerContractResponse(
        id=str(owner.id),
        email=owner.email,
        zone_id=owner.zone_id,
        first_name=owner.first_name,
        last_name=owner.last_name,
        account_type=owner.account_type.value,
        role=owner.role.value,
        account_owner_id=owner.account_owner_id or owner.id,
        address=owner.address,
        phone=owner.phone,
        map_center=map_center,
        active=owner.active,
        expired=owner.expired,
        created_at=owner.created_at,
        updated_at=owner.updated_at,
        api_key=owner.api_key,
    )
    return success_response(data.model_dump())


@router.post(
    "/zones",
    status_code=status.HTTP_201_CREATED,
    response_model=ContractSuccessAnyResponse,
    summary="Create contract zone",
    description="Create main/secondary zones during setup wizard flows.",
    responses={
        status.HTTP_401_UNAUTHORIZED: {
            "description": "Authentication token missing or invalid.",
        },
        status.HTTP_403_FORBIDDEN: {
            "description": "Caller is not allowed to create this zone.",
        },
        status.HTTP_422_UNPROCESSABLE_ENTITY: {
            "description": "Zone payload validation failed.",
        },
    },
    response_description="Success envelope containing created zone payload.",
)
async def post_zones(
    payload: ZoneUpsertRequest,
    owner: Owner = Depends(require_auth),
    db: Session = Depends(get_db),
):
    data = controllers.create_zone(db, owner, payload.model_dump())
    db.commit()
    return success_response(data)


@router.put(
    "/zones/{zone_id}",
    response_model=ContractSuccessAnyResponse,
    summary="Update contract zone",
    description="Replace/update an existing zone definition for setup wizard flows.",
    responses={
        status.HTTP_401_UNAUTHORIZED: {
            "description": "Authentication token missing or invalid.",
        },
        status.HTTP_403_FORBIDDEN: {
            "description": "Caller is not allowed to update this zone.",
        },
        status.HTTP_404_NOT_FOUND: {
            "description": "Requested zone does not exist.",
        },
        status.HTTP_422_UNPROCESSABLE_ENTITY: {
            "description": "Zone payload validation failed.",
        },
    },
    response_description="Success envelope containing updated zone payload.",
)
async def put_zone(
    zone_id: str,
    payload: ZoneUpsertRequest,
    owner: Owner = Depends(require_auth),
    db: Session = Depends(get_db),
):
    data = controllers.update_zone(db, owner, zone_id, payload.model_dump())
    db.commit()
    return success_response(data)


@router.delete(
    "/zones/{zone_id}",
    response_model=ContractSuccessAnyResponse,
    summary="Delete contract zone",
    description="Delete an existing contract-managed zone by shared zone id.",
    responses={
        status.HTTP_401_UNAUTHORIZED: {
            "description": "Authentication token missing or invalid.",
        },
        status.HTTP_403_FORBIDDEN: {
            "description": "Caller is not allowed to delete this zone.",
        },
        status.HTTP_404_NOT_FOUND: {
            "description": "Requested zone does not exist.",
        },
    },
    response_description="Success envelope confirming zone deletion.",
)
async def remove_zone(zone_id: str, owner: Owner = Depends(require_auth), db: Session = Depends(get_db)):
    controllers.delete_zone(db, owner, zone_id)
    db.commit()
    return success_response({"deleted": True, "zoneId": zone_id})


@router.post(
    "/messages",
    status_code=status.HTTP_201_CREATED,
    response_model=ContractSuccessAnyResponse | ZoneMessageResponse,
    summary="Create contract message (legacy envelope or chat / guest-thread)",
    description=(
        "**`MessageCreateRequest`** (`zoneId`, `type`, `text`, …): legacy contract envelope via **`success_response`**.\n\n"
        "**`ChatMessageCreateRequest`**: member **`Message`** when **`guest_id`** is omitted; "
        "when **`guest_id`** and **`zone_id`** / **`zoneId`** are set, creates **`ZoneMessageEvent`** **CHAT** only "
        "(**PERMISSION** is server-generated — same rejection semantics as **`POST /messages`**). "
        "**`ZoneMessageResponse`** includes **`guest_id`** and UUID **`id`**; aligns with **`GET /messages`** merged inbox when **`MESSAGES_INBOX_MERGE_GUEST_ACCESS_CHAT=true`**. "
        "Use **`message_type`** if **`type`** is omitted.\n\n"
        "See **`ChatMessageCreateRequest`** examples in Swagger."
    ),
    responses={
        status.HTTP_401_UNAUTHORIZED: {
            "description": "Authentication token missing or invalid.",
        },
        status.HTTP_403_FORBIDDEN: {
            "description": "Receiver outside scope, member cannot administer **zone_id** for guest post, or policy **FORBIDDEN**.",
        },
        status.HTTP_404_NOT_FOUND: {
            "description": "Sender / receiver not found, or **GUEST_NOT_FOUND** for bad **guest_id** + zone.",
        },
        status.HTTP_422_UNPROCESSABLE_ENTITY: {
            "description": "Validation failed (including **MISSING_ZONE_FOR_GUEST**, **INVALID_MESSAGE_TYPE_FOR_GUEST**).",
        },
    },
    response_description=(
        "**`{ status, data }`** for legacy contract payload, or **`ZoneMessageResponse`** for chat / guest-thread **CHAT** "
        "(UUID **`id`**, **`guest_id`**, **`category`:** **`Access`**)."
    ),
)
async def post_messages(
    payload: MessageCreateRequest | ChatMessageCreateRequest = Body(...),
    owner: Owner = Depends(require_auth),
    db: Session = Depends(get_db),
):
    # Backward-compatible contract payload.
    if isinstance(payload, MessageCreateRequest):
        data = controllers.create_message(db, owner, payload.model_dump())
        db.commit()
        await ws_manager.broadcast_message(payload.zoneId, data)
        return success_response(data)

    # Compatibility path for clients sending the chat payload shape.
    chat_payload = payload
    sender = owner_crud.get_owner(db, owner.id)
    if not sender:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Sender owner not found",
        )

    if (chat_payload.guest_id or "").strip():
        z_req = (chat_payload.zone_id or "").strip()
        if not z_req:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail={
                    "error_code": "MISSING_ZONE_FOR_GUEST",
                    "message": "zone_id is required when guest_id is set.",
                },
            )
        try:
            guest_canonical = normalize_message_type(chat_payload.type or "")
        except ValueError as exc:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail={"error_code": "INVALID_MESSAGE_TYPE", "message": "Unsupported message type."},
            ) from exc
        if guest_canonical == CanonicalMessageType.PERMISSION:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail={
                    "error_code": "PERMISSION_MANUAL_DISABLED",
                    "message": "PERMISSION messages are server-generated only for guest workflow transitions.",
                },
            )
        if guest_canonical != CanonicalMessageType.CHAT:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail={
                    "error_code": "GUEST_MESSAGE_TYPE_NOT_ALLOWED",
                    "message": "Guest thread messaging supports only CHAT.",
                },
            )
        guest_result = guest_api_service.create_member_to_guest_zone_message(
            db,
            sender=sender,
            zone_id=z_req,
            guest_id=chat_payload.guest_id.strip(),
            text=chat_payload.message,
            msg_type=chat_payload.type or "",
        )
        if isinstance(guest_result, dict):
            code = guest_result.get("__reject__")
            msg = str(guest_result.get("message") or "Request failed")
            if code == "forbidden":
                raise HTTPException(
                    status_code=status.HTTP_403_FORBIDDEN,
                    detail={"error_code": "FORBIDDEN", "message": msg},
                )
            if code == "not_found":
                raise HTTPException(
                    status_code=status.HTTP_404_NOT_FOUND,
                    detail={"error_code": "GUEST_NOT_FOUND", "message": msg},
                )
            if code == "permission_manual_disabled":
                raise HTTPException(
                    status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                    detail={"error_code": "PERMISSION_MANUAL_DISABLED", "message": msg},
                )
            if code == "invalid_type":
                raise HTTPException(
                    status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                    detail={"error_code": "GUEST_MESSAGE_TYPE_NOT_ALLOWED", "message": msg},
                )
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail={"error_code": "INVALID_GUEST_MESSAGE", "message": msg},
            )
        event = guest_result
        eid = event.id
        db.commit()
        if settings.MESSAGES_INBOX_MERGE_GUEST_ACCESS_CHAT:
            zr = db.get(ZoneMessageEvent, eid)
            if zr:
                await guest_api_service.notify_access_chat_inbox_ws(db, zr)
        return guest_api_service.zone_message_event_to_member_zone_message_response(event, db=db)

    normalized_chat_payload = ZoneMessageCreate(
        message=chat_payload.message,
        visibility=chat_payload.visibility,
        type=chat_payload.type,
        receiver_id=chat_payload.receiver_id,
    )
    try:
        derived_scope = type_scope(normalize_message_type(normalized_chat_payload.type or ""))
    except ValueError as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail={"error_code": "INVALID_MESSAGE_TYPE", "message": "Unsupported message type."},
        ) from exc
    if derived_scope == MessageScope.PRIVATE and normalized_chat_payload.receiver_id is None:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail={
                "error_code": "MISSING_RECIPIENT_FOR_PRIVATE_TYPE",
                "message": "receiver_id is required for private-scope message types.",
            },
        )
    if derived_scope == MessageScope.PUBLIC and normalized_chat_payload.receiver_id is not None:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail={
                "error_code": "INVALID_TYPE_SCOPE_COMBINATION",
                "message": "receiver_id must be omitted for public-scope message types.",
            },
        )

    if (
        normalized_chat_payload.visibility is not None
        and normalized_chat_payload.visibility.value != derived_scope.value
    ):
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail={
                "error_code": "INVALID_VISIBILITY_FOR_TYPE",
                "message": "visibility does not match the inferred message type scope.",
            },
        )

    if chat_payload.receiver_id is not None:
        receiver = owner_crud.get_owner(db, chat_payload.receiver_id)
        if not receiver:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Receiver owner not found",
            )
        if not receiver.active:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail={
                    "error_code": "RECEIVER_INACTIVE",
                    "message": "Receiver account is inactive.",
                },
            )
        if receiver.id == sender.id:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail={
                    "error_code": "INVALID_RECEIVER_SELF",
                    "message": "Sender cannot message self.",
                },
            )
        if not can_message_owner(sender, receiver, require_same_zone=True):
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail={
                    "error_code": "RECEIVER_OUTSIDE_ALLOWED_SCOPE",
                    "message": "Receiver is outside sender account or zone scope.",
                },
            )
        if message_block_service.is_delivery_blocked(
            db,
            recipient_owner_id=receiver.id,
            sender_owner_id=sender.id,
            message_type=normalize_message_type(normalized_chat_payload.type or "").value,
        ):
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail={
                    "error_code": "MESSAGE_BLOCKED_BY_RECIPIENT",
                    "message": "Recipient has blocked this message or sender.",
                },
            )

    db_message = message_crud.create_message(
        db,
        sender_id=sender.id,
        payload=normalized_chat_payload,
    )
    db.commit()
    canonical_type = normalize_message_type(db_message.message_type)

    return ZoneMessageResponse(
        id=db_message.id,
        zone_id=sender.zone_id,
        sender_id=db_message.sender_id,
        receiver_id=db_message.receiver_id,
        type=db_message.message_type,
        category=type_category(canonical_type).value,
        scope=type_scope(canonical_type).value,
        visibility=db_message.visibility,
        message=db_message.message,
        created_at=db_message.created_at,
    )


@router.get(
    "/messages/new",
    response_model=ContractSuccessAnyResponse,
    summary="Get new contract messages",
    description="Return messages created after the supplied ISO datetime cursor.",
    responses={
        status.HTTP_401_UNAUTHORIZED: {
            "description": "Authentication token missing or invalid.",
        },
        status.HTTP_422_UNPROCESSABLE_ENTITY: {
            "description": "Invalid 'since' cursor format.",
        },
    },
    response_description="Success envelope containing messages newer than the cursor.",
)
async def get_new_messages(since: str = Query(...), db: Session = Depends(get_db), owner: Owner = Depends(require_auth)):
    _ = owner
    return success_response(controllers.get_new_messages(db, since))


@router.get(
    "/members",
    response_model=ContractSuccessMembersResponse,
    summary="List members visible to caller",
    description=(
        "Returns owners visible to the caller based on account role policy. "
        "Administrators see all members in their account; users see only themselves. "
        "By default includes both active and inactive members; "
        "filter by active state using query parameter active=true/false. "
        "Each item includes profile fields, active state, optional location snapshot, and active zones."
    ),
)
async def get_members(
    active: bool | None = Query(
        default=None,
        description="Optional active-state filter. Omit to return all members, or set true/false.",
    ),
    owner: Owner = Depends(require_auth),
    db: Session = Depends(get_db),
):
    return success_response(controllers.get_members(db, owner, active=active))


@router.post(
    "/members/location",
    response_model=ContractSuccessMemberLocationResponse,
    summary="Upsert current member location",
    description=(
        "Creates or updates the authenticated user's location snapshot used by the "
        "members list and zone evaluation workflows."
    ),
)
async def post_member_location(
    payload: MemberLocationRequest,
    owner: Owner = Depends(require_auth),
    db: Session = Depends(get_db),
):
    data = controllers.update_location(db, owner, payload.latitude, payload.longitude)
    db.commit()
    return success_response(data)


@router.post(
    "/devices/push-token",
    response_model=ContractSuccessAnyResponse,
    summary="Register push token",
    description="Register or update a mobile push token for the authenticated owner.",
    responses={
        status.HTTP_401_UNAUTHORIZED: {
            "description": "Authentication token missing or invalid.",
        },
        status.HTTP_422_UNPROCESSABLE_ENTITY: {
            "description": "Invalid push token payload.",
        },
    },
    response_description="Success envelope containing registered token result.",
)
async def post_push_token(
    payload: PushTokenRequest,
    owner: Owner = Depends(require_auth),
    db: Session = Depends(get_db),
):
    data = controllers.register_push_token(db, owner, payload.token, payload.platform)
    db.commit()
    return success_response(data)


class PushTestRequest(BaseModel):
    """Diagnostic test push request body.

    Used by the Settings → "Send test push" button to verify end-to-end
    delivery (Expo → FCM/APNS → device system tray) without needing a second
    account. `delay_seconds` lets the caller close the app before the push
    fires, so the killed-app system-tray code path is exercised.
    """

    title: str | None = Field(
        default=None,
        max_length=80,
        description="Optional notification title; defaults to 'Hex Zone test push'.",
    )
    message: str | None = Field(
        default=None,
        max_length=240,
        description="Optional body text; defaults to a generic confirmation string.",
    )
    delay_seconds: int = Field(
        default=0,
        ge=0,
        le=30,
        description=(
            "Wait this many seconds before sending so the user can close the "
            "app and verify killed-app push delivery. Capped at 30s."
        ),
    )


@router.post(
    "/devices/push-token/test",
    response_model=ContractSuccessAnyResponse,
    summary="Send a diagnostic test push to the authenticated owner",
    description=(
        "Sends a self-test push to every active token registered for the "
        "authenticated owner. Returns counts so the client can show "
        "`tokens`/`push_sent`/`push_failed`. Pass `delay_seconds` to schedule "
        "the send a few seconds after the response so you can close the app "
        "and verify a system-tray notification appears in the killed state.\n\n"
        "**Common failure causes:** if `tokens > 0` but no notification "
        "arrives, the most likely cause is that the **FCM v1 service account "
        "key** has not been uploaded on EAS for this Expo project. Run "
        "`eas credentials` → Android → *Push Notifications: FCM V1* and "
        "upload the service account JSON from Firebase → Project settings → "
        "Service accounts → Generate new private key."
    ),
    responses={
        status.HTTP_401_UNAUTHORIZED: {
            "description": "Authentication token missing or invalid.",
        },
    },
    response_description=(
        "Success envelope with `{tokens, push_sent, push_failed, scheduled?}`."
    ),
)
async def post_push_token_test(
    background_tasks: BackgroundTasks,
    payload: PushTestRequest = Body(default_factory=PushTestRequest),
    owner: Owner = Depends(require_auth),
    db: Session = Depends(get_db),
):
    from app.database import session_maker
    from app.services import push_notification_service

    title = (payload.title or "").strip() or "Hex Zone test push"
    body = (payload.message or "").strip() or (
        "If you can read this, push delivery works end to end."
    )

    if payload.delay_seconds <= 0:
        result = await push_notification_service.send_test_push_to_owner(
            db, owner.id, title=title, body=body
        )
        return success_response(result)

    owner_id = int(owner.id)
    delay = int(payload.delay_seconds)

    async def _delayed_test_push() -> None:
        try:
            await asyncio.sleep(delay)
            bg_db = session_maker()
            try:
                result = await push_notification_service.send_test_push_to_owner(
                    bg_db, owner_id, title=title, body=body
                )
                logger = push_notification_service.logger
                logger.info("Delayed test push finished for owner %s: %s", owner_id, result)
            finally:
                bg_db.close()
        except Exception:
            push_notification_service.logger.exception(
                "Delayed test push failed for owner %s", owner_id
            )

    background_tasks.add_task(_delayed_test_push)

    from app.models import PushToken

    token_count = (
        db.query(PushToken)
        .filter(PushToken.owner_id == owner_id, PushToken.active.is_(True))
        .count()
    )
    return success_response(
        {
            "scheduled": True,
            "delay_seconds": delay,
            "tokens": token_count,
            "channel_id": push_notification_service.ANDROID_DEFAULT_PUSH_CHANNEL,
        }
    )


# ---------------------------------------------------------------------------
# Owner application settings (broadcast identity, structured home address,
# shared-notification integration, quick-alert messages). Persisted per owner
# so they survive a new device / cleared browser localStorage.
# ---------------------------------------------------------------------------


class AddressSettingsModel(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    number_street: str = Field(default="", validation_alias=AliasChoices("numberStreet", "number_street"), serialization_alias="numberStreet")
    street_name: str = Field(default="", validation_alias=AliasChoices("streetName", "street_name"), serialization_alias="streetName")
    city: str = Field(default="")
    state_province: str = Field(default="", validation_alias=AliasChoices("stateProvince", "state_province"), serialization_alias="stateProvince")
    city_code: str = Field(default="", validation_alias=AliasChoices("cityCode", "city_code"), serialization_alias="cityCode")


class SharedNotificationSettingsModel(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    hid: str = Field(default="")
    network_id: str = Field(default="", validation_alias=AliasChoices("networkId", "network_id"), serialization_alias="networkId")
    api_key: str = Field(default="", validation_alias=AliasChoices("apiKey", "api_key"), serialization_alias="apiKey")
    webhook: str = Field(default="")
    periodical_check_sec: str = Field(default="86400", validation_alias=AliasChoices("periodicalCheckSec", "periodical_check_sec"), serialization_alias="periodicalCheckSec")


class AppSettingsModel(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    broadcast_name: str = Field(default="", validation_alias=AliasChoices("broadcastName", "broadcast_name"), serialization_alias="broadcastName")
    address: AddressSettingsModel = Field(default_factory=AddressSettingsModel)
    shared_notification: SharedNotificationSettingsModel = Field(
        default_factory=SharedNotificationSettingsModel,
        validation_alias=AliasChoices("sharedNotification", "shared_notification"),
        serialization_alias="sharedNotification",
    )
    quick_messages: dict[str, str] = Field(
        default_factory=dict,
        validation_alias=AliasChoices("quickMessages", "quick_messages"),
        serialization_alias="quickMessages",
    )


def _seed_address_from_owner(raw_address: str | None) -> AddressSettingsModel:
    """Best-effort split of the single signup address string into structured parts.

    The signup form only captures one free-form string (e.g.
    "169 Fred Young Drive, Toronto, Ontario, M3L 0A6"), so this seeds the
    structured fields on first load. The user can correct and save afterwards.
    """
    parts = [p.strip() for p in (raw_address or "").split(",")]
    first = parts[0] if len(parts) > 0 else ""
    city = parts[1] if len(parts) > 1 else ""
    state_province = parts[2] if len(parts) > 2 else ""
    city_code = parts[3] if len(parts) > 3 else ""

    number = ""
    street = first
    match = re.match(r"^\s*(\d+[A-Za-z]?)\s+(.*)$", first)
    if match:
        number = match.group(1)
        street = match.group(2).strip()

    return AddressSettingsModel(
        number_street=number,
        street_name=street,
        city=city,
        state_province=state_province,
        city_code=city_code,
    )


def _address_model_to_single_line(addr: AddressSettingsModel) -> str:
    """Compose the structured address fields into one signup-style string."""
    line1 = " ".join(
        part
        for part in [(addr.number_street or "").strip(), (addr.street_name or "").strip()]
        if part
    )
    parts = [line1] if line1 else []
    for part in [addr.city, addr.state_province, addr.city_code]:
        value = (part or "").strip()
        if value:
            parts.append(value)
    return ", ".join(parts)


def _smart_home_device_for_owner(db: Session, owner_id: int) -> Device | None:
    """Prefer a dedicated smart-home hardware id over mobile/browser clients."""
    devices = (
        db.query(Device)
        .filter(Device.owner_id == owner_id, Device.active.is_(True))
        .order_by(Device.created_at.asc())
        .all()
    )
    for device in devices:
        hid = (device.hid or "").strip().upper()
        if hid and not hid.startswith(("MOB-", "WEB-")):
            return device
    return devices[0] if devices else None


def _seed_empty_shared_fields(
    sn: SharedNotificationSettingsModel,
    owner: Owner,
    db: Session,
) -> None:
    """Fall back to the owner's live account data for any blank integration field.

    Smart-home integration values shown on the Settings page:

    - API Key        -> ``owners.api_key`` (authenticates the device to Hex Zone)
    - HID            -> smart-home device hardware id (``devices.hid``)
    - Network ID     -> the owner's zone id (``owners.zone_id``)

    Any value the operator has saved (non-empty) always takes precedence.
    """
    if not sn.api_key:
        sn.api_key = owner.api_key or ""

    if not sn.hid:
        device = _smart_home_device_for_owner(db, owner.id)
        sn.hid = (device.hid if device else "") or ""

    if not sn.network_id:
        sn.network_id = (owner.zone_id or "").strip()


def _load_quick_messages(db: Session, owner_id: int) -> dict[str, str]:
    """Read this owner's quick-alert templates from the `messages` table.

    Templates are `messages` rows flagged `is_template=True`, one per message
    type, keyed here by the canonical message type string.
    """
    rows = (
        db.query(Message)
        .filter(Message.sender_id == owner_id, Message.is_template.is_(True))
        .all()
    )
    return {row.message_type: row.message or "" for row in rows}


def _save_quick_messages(db: Session, owner_id: int, quick_messages: dict[str, str]) -> None:
    """Replace this owner's quick-alert templates in the `messages` table.

    Existing template rows are removed and re-created from the payload so the
    stored set always matches what the client sent. Blank bodies are skipped.
    """
    db.query(Message).filter(
        Message.sender_id == owner_id, Message.is_template.is_(True)
    ).delete(synchronize_session=False)

    for raw_type, body in (quick_messages or {}).items():
        text = (body or "").strip()
        if not text:
            continue
        try:
            canonical = normalize_message_type(raw_type)
        except ValueError:
            continue
        scope = type_scope(canonical)
        db.add(
            Message(
                sender_id=owner_id,
                receiver_id=owner_id,
                visibility=MessageVisibility(scope.value),
                scope=scope,
                message_type=canonical.value,
                message=text,
                is_template=True,
            )
        )


def _owner_to_settings_model(owner: Owner, db: Session) -> AppSettingsModel:
    """Build the Settings-page payload from the owner profile + live sources.

    - broadcast name / address / webhook / periodical check -> `owners`
    - HID / network id / api key -> derived from smart-home device / zone_id / api_key
    - quick messages -> `messages` template rows
    """
    model = AppSettingsModel(
        broadcast_name=(owner.broadcast_name or "").strip(),
        address=_seed_address_from_owner(owner.address),
        shared_notification=SharedNotificationSettingsModel(
            webhook=(owner.sn_webhook or "").strip(),
            periodical_check_sec=owner.sn_periodical_check_sec or "86400",
        ),
        quick_messages=_load_quick_messages(db, owner.id),
    )
    _seed_empty_shared_fields(model.shared_notification, owner, db)
    return model


@router.get(
    "/me/settings",
    summary="Get owner application settings",
    description=(
        "Return the authenticated owner's broadcast identity, structured home "
        "address, smart-home integration, and quick-alert messages. "
        "Broadcast name + address + webhook/periodical check come from the "
        "`owners` row; HID/network id/api key are derived from the owner's "
        "smart-home device, zone id and account api key; quick messages come from the "
        "`messages` table (template rows)."
    ),
)
async def get_my_settings(
    owner: Owner = Depends(require_auth),
    db: Session = Depends(get_db),
):
    model = _owner_to_settings_model(owner, db)
    return success_response(model.model_dump(by_alias=True))


@router.put(
    "/me/settings",
    summary="Update owner application settings",
    description=(
        "Persist the authenticated owner's editable settings. Broadcast name, "
        "address and the webhook / periodical-check values are stored on the "
        "`owners` row; quick messages are stored as `messages` template rows. "
        "HID and API key are derived and ignored on save. Network ID is saved "
        "to `owners.zone_id` only for Private (system administrator) accounts."
    ),
)
async def put_my_settings(
    payload: AppSettingsModel,
    owner: Owner = Depends(require_auth),
    db: Session = Depends(get_db),
):
    owner.broadcast_name = (payload.broadcast_name or "").strip()

    formatted_address = _address_model_to_single_line(payload.address)
    if formatted_address:
        owner.address = formatted_address
        try:
            sync_owner_home_from_address(owner)
        except Exception as exc:  # pragma: no cover - never block settings save
            logging.getLogger(__name__).warning(
                "Home geocode failed after settings save for owner %s: %s",
                owner.id,
                exc,
            )

    owner.sn_webhook = (payload.shared_notification.webhook or "").strip()
    owner.sn_periodical_check_sec = (
        (payload.shared_notification.periodical_check_sec or "86400").strip() or "86400"
    )

    requested_network_id = (payload.shared_notification.network_id or "").strip()
    if requested_network_id and requested_network_id != (owner.zone_id or "").strip():
        assert_owner_may_edit_network_id(owner)
        owner.zone_id = requested_network_id

    _save_quick_messages(db, owner.id, payload.quick_messages)

    db.commit()
    db.refresh(owner)
    model = _owner_to_settings_model(owner, db)
    return success_response(model.model_dump(by_alias=True))
